# Generated by Django 3.2.5 on 2021-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png, jpg 파일을 업로드해주세요.', upload_to='account/avatar/%Y-%m-%d'),
        ),
    ]
